version: 2.5.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- ps: 
deploy:
- provider: NuGet
  api_key:
    secure: jkWeAMNQbdidtlasCWp7Wq/gqZz2h7DO40WgUSqJDWPN48dTPyMZ7Mwdh7FmDcKU
  on:
    branch: master